//
//  AWSFacebookSignInProvider.h
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import <Foundation/Foundation.h>
#import "AWSSignInProvider.h"

NS_ASSUME_NONNULL_BEGIN

/**
 * `AWSFacebookSignInProvider` adopts the `AWSSignInProvider` protocol.
 *
 * It works with the FacebookLoginSDK internally and uses the Facebook App ID specified in the info.plist file.
 */
@interface AWSFacebookSignInProvider : NSObject <AWSSignInProvider>

/**
 Fetches the singleton instance of AWSFacebookSignInProvider.
 
 @return the singleton instance of AWSFacebookSignInProvider
 */
+ (instancetype)sharedInstance;

/**
 Sets the login behavior of the Facebook SignIn SDK.
 Choices are listed in enum FBSDKLoginBehavior.
 Default behaviors for iOS:
 9+ SFSafariViewController used.
 8  WebViewController used.
 @loginBehavior a FBSDKLoginBehavior enum entry
 */
- (void)setLoginBehavior:(NSUInteger)loginBehavior;

/**
 Sets the permissions requested during login.
 Default behavior is no permissions are required.
 */
- (void)setPermissions:(NSArray *)permissions;

/**
 Sets the ViewController used for Facebook SignIn.
 Defaults to nil and handled by Facebook SDK.
 */
- (void)setViewControllerForFacebookSignIn:(UIViewController *)signInViewController;

@end

NS_ASSUME_NONNULL_END
