//
//  Graffiti.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class Graffiti: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _lastUpdatedDate: NSNumber?
    var _contents: String?
    var _contributors: Set<String>?
    var _drawingId: String?
    
    class func dynamoDBTableName() -> String {

        return "fullsample-mobilehub-1182182639-Graffiti"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_lastUpdatedDate"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "userId",
               "_lastUpdatedDate" : "lastUpdatedDate",
               "_contents" : "contents",
               "_contributors" : "contributors",
               "_drawingId" : "drawingId",
        ]
    }
}
