//
//  NoSQLSampleDataGenerator.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation

let NoSQLSampleDataGeneratorSampleDataStringPrefix: String = "demo"
let NoSQLSampleDataGeneratorSampleDataNumberMinimum: UInt32 = 1111000000
let NoSQLSampleDataGeneratorSampleDataNumberMaximum: UInt32 = 1111999999
let NoSQLSampleDataGeneratorRandomNumberMaximum: UInt32 = NoSQLSampleDataGeneratorSampleDataNumberMaximum - NoSQLSampleDataGeneratorSampleDataNumberMinimum
let NoSQLSampleDataGeneratorSampleDataPartition: UInt8 = 4

var NoSQLSampleDataGeneratorSampleStringValues: [String] = ["apple", "banana", "orange", "pear", "pineapple", "lemon",
                                                             "cherry", "avocado", "blueberry", "raspberry", "grape", "watermelon", "papaya"]

class NoSQLSampleDataGenerator {
    
    // MARK: - Internal Methods
    
    class func randomNumber() -> UInt32 {
        return arc4random_uniform(NoSQLSampleDataGeneratorRandomNumberMaximum)
    }
    
    // MARK:- Partition Methods
    
    class func randomPartitionSampleNumber() -> NSNumber {
        return NSNumber(unsignedInt: NoSQLSampleDataGeneratorSampleDataNumberMinimum + arc4random_uniform(UInt32(NoSQLSampleDataGeneratorSampleDataPartition)) + 1)
    }
    
    class func randomPartitionSampleStringWithAttributeName(attributeName: String) -> String {
        return "\(NoSQLSampleDataGeneratorSampleDataStringPrefix)-\(attributeName)-\(arc4random_uniform(UInt32(NoSQLSampleDataGeneratorSampleDataPartition)) + 1)"
    }
    
    class func randomPartitionSampleBinary() -> NSData {
        return "\(NoSQLSampleDataGeneratorSampleDataStringPrefix)-\(randomPartitionSampleNumber())".dataUsingEncoding(NSUTF8StringEncoding)!
    }
    
    // MARK: - General Methods
    
    class func randomSampleNumber() -> NSNumber {
        return NSNumber(unsignedInt: NoSQLSampleDataGeneratorSampleDataNumberMinimum + randomNumber())
    }
    
    class func randomSampleStringWithAttributeName(attributeName: String) -> String {
        return "\(NoSQLSampleDataGeneratorSampleDataStringPrefix)-\(attributeName)-\(randomNumber().formattedIntegerString())"
    }
    
    class func randomSampleBOOL() -> NSNumber {
        // If random number is even number then return true, false for odd numbers
        return self.randomNumber() % 2 == 0
    }
    
    class func randomSampleBinary() -> NSData {
        return "\(NoSQLSampleDataGeneratorSampleDataStringPrefix)-\(randomSampleNumber())".dataUsingEncoding(NSUTF8StringEncoding)!
    }
    
    class func randomSampleStringSet() -> Set<String> {
        var set: Set<String> = Set()
        for value in randomSampleStringArray() {
            set.insert(value)
        }
        return set
    }
    
    class func randomSampleNumberSet() -> Set<NSNumber> {
        var numberSet: Set<NSNumber> = Set()
        let arrayCount: UInt32 = arc4random_uniform(UInt32(NoSQLSampleDataGeneratorSampleStringValues.count)) + 1
        for _ in 0..<arrayCount {
            numberSet.insert(self.randomSampleNumber())
        }
        return numberSet
    }
    
    class func randomSampleBinarySet() -> Set<NSData> {
        var set: Set<NSData> = Set()
        for randomString in randomSampleStringArray() {
            set.insert(randomString.dataUsingEncoding(NSUTF8StringEncoding)!)
        }
        return set
    }
    
    class func randomSampleStringArray() -> [String] {
        var stringArray: [String] = []
        // Get a random number of insertion items
        let items: Int = Int(arc4random_uniform(UInt32(NoSQLSampleDataGeneratorSampleStringValues.count / 2)) + 1)
        // Insert items for corresponding count
        for _ in 0..<items {
            stringArray.append(NoSQLSampleDataGeneratorSampleStringValues[Int(arc4random_uniform(UInt32(NoSQLSampleDataGeneratorSampleStringValues.count)))])
        }
        return stringArray

    }
    
    class func randomSampleMap() -> [String: String] {
        var dictionary: [String: String] = [:]
        let dictionaryCount: UInt32 = arc4random_uniform(UInt32(NoSQLSampleDataGeneratorSampleStringValues.count)) + 1
        for index in 0..<dictionaryCount {
            let key: String = NoSQLSampleDataGeneratorSampleStringValues[Int(index)]
            dictionary[key] = randomSampleStringWithAttributeName(key)
        }
        return dictionary
    }
}

extension UInt32 {
    private func formattedIntegerString() -> String {
        return String(format: "%06d", self)
    }
    
    private func formattedLongString() -> String {
        return String(format: "%06llu", self)
    }
}
